resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne.git
    endpoint: JFolberth
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
    - template: adf_template.yml
